version: '3.8'

services:
  database:
    image: postgres:17
    container_name: prototipo_tcc_database_container
    restart: always
    environment:
      POSTGRES_USER: prototipo_tcc_user
      POSTGRES_PASSWORD: Pswd_Prttp_Tcc_587964$
      POSTGRES_DB: prototipo_tcc_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - prototipo_tcc_data:/var/lib/postgresql/data
volumes:
  prototipo_tcc_data: